### ISSUE TITLE
cannot import python module

### ISSUE THREAD

**Issue by wildeyevr** [mitsuba-renderer/nanogui#110]
installed with setup.py (pip install .) I get the following traceback when trying to import the module

>>> import nanogui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/proscans/nanogui/nanogui/__init__.py", line 3, in <module>
    _import('nanogui.nanogui_ext')
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'nanogui.nanogui_ext'

**Comment by wjakob** [comment]
That looks to me like a python version mismatch (extension built for one version of python, then imported in another).

Probably the easiest way to get the library is via `pip install`.
